name: deploy-to-deta

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DETA_ACCESS_TOKEN: ${{ secrets.DETA_TOKEN }}
      DETA_KEY: ${{ secrets.DETA_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Deta CLI
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
    - name: Deploy-Backend
      run: |
        ~/.deta/bin/deta clone --name backend --project default tmp/
        ls
        cp -r tmp/.deta backend/
        cp tmp/main.py backend/
        cp tmp/requirements.txt backend/
        ~/.deta/bin/deta deploy backend

    - name: Deploy-Cron
      run: |
        ~/.deta/bin/deta clone --name cron-job --project default tmp2/
        ls -a
        cp -r tmp2/.deta cron-job/
        cp tmp2/main.py cron-job/
        cp tmp2/requirements.txt cron-job/
        ~/.deta/bin/deta deploy cron-job

    - name: Set up environment variables backend
      run: |
        cd backend
        echo DETA_KEY=$DETA_KEY >> .env
        ~/.deta/bin/deta update --env .env

    - name: Set up environment variables cron
      run: |
        cd cron-job
        echo DETA_KEY=$DETA_KEY >> .env
        ~/.deta/bin/deta update --env .env
